name: On PR - test RiveCodeGenerator

on:
  workflow_call:

jobs:
  build_rive_code_generator_mac:
    name: Build Rive Code Generator MacOS
    runs-on: ghcr.io/cirruslabs/macos-runner:sonoma
    steps:
      - uses: actions/checkout@v3
      # - name: Configure venv
      #   run: |
      #     python3 -m venv .venv
      #     source .venv/bin/activate
      #     echo PATH=$PATH >> $GITHUB_ENV
      # - name: install ply
      #   run: pip3 install ply
      - name: Build
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        working-directory: ./build
        run: ./build.sh release
      - name: Test
        working-directory: ./test
        run: ./test.sh
      - uses: actions/upload-artifact@v4
        with:
          name: rive_code_generator_macosx
          path: ./build/out/lib/release/rive_code_generator