name: On PR - test RiveCodeGenerator

on:
  workflow_call:

jobs:
  build:
    name: Build Rive Code Generator MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: |
          git submodule init
          git submodule update --recursive      
      # - name: Configure venv
      #   run: |
      #     python3 -m venv .venv
      #     source .venv/bin/activate
      #     echo PATH=$PATH >> $GITHUB_ENV
      # - name: install ply
      #   run: pip3 install ply
      - name: Build for MacOS
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
        working-directory: ./build
        run: ./build.sh release

      - name: Test for MacOS
        working-directory: ./test
        run: ./test.sh

      - name: Upload artifact for macosx
        uses: actions/upload-artifact@v4
        with:
          name: rive_code_generator_macosx
          path: ./build/out/lib/release/rive_code_generator